language: php
php:
    - 5.6
    - 5.5
    - 5.4

before_install:
    - 'php -S localhost:8000 > /tmp/server.log 2>&1 &'

install:
    - composer install --no-dev

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
